export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const ITEMS_LOADING = "ITEMS_LOADING";
export const COMPONENT_LOADING = "COMPONENT_LOADING";

export const ADD_DETAILS = "ADD_DETAILS";
export const GET_DETAILS = "GET_DETAILS";

export const ADD_PRODUCT_DETAILS = "ADD_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const GET_PRODUCT_DETAILS_BY_ID = "GET_PRODUCT_DETAILS_BY_ID";

export const FETCH_PRODUCT = "FETCH_POST";
export const FETCH_PRODUCT_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_POST_FAILURE";
export const RESET_ACTIVE_PRODUCT = "RESET_ACTIVE_POST";

export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";
export const RESET_PRODUCTS = "RESET_PRODUCTS";

export const SET_PRODUCT_TO_CART = "SET_PRODUCT_TO_CART";
export const SET_PRODUCT_TO_CART_SUCCESS = "SET_PRODUCT_TO_CART_SUCCESS";
export const SET_PRODUCT_TO_CART_FAILURE = "SET_PRODUCT_TO_CART_FAILURE";
export const RESET_CART_PRODUCTS = "RESET_CART_PRODUCTS";

export const FETCH_CART_PRODUCTS = "FETCH_CART_PRODUCTS";
export const FETCH_CART_PRODUCTS_SUCCESS = "FETCH_CART_PRODUCTS_SUCCESS";
export const FETCH_CART_PRODUCTS_FAILURE = "FETCH_CART_PRODUCTS_FAILURE";
export const RESET_FETCH_CART_PRODUCTS = "RESET_FETCH_CART_PRODUCTS";

export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";
export const ADD_NEW_USER_FAILURE = "ADD_NEW_USER_FAILURE";
export const RESET_ADD_NEW_USER = "RESET_ADD_NEW_USER";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const RESET_USER_LOGIN = "RESET_USER_LOGIN";
